--Tabela de produtos
CREATE TABLE PRODUTOS (
    ID              INTEGER NOT NULL,
    DESCRICAO       VARCHAR(100) NOT NULL,
    ESTOQUE_ATUAL   INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID)
);

--Tabela de movimentações
CREATE TABLE MOVIMENTACOES_ESTOQUE (
    ID                INTEGER NOT NULL,
    ID_PRODUTO        INTEGER NOT NULL,
    DATA_HORA         TIMESTAMP NOT NULL,
    TIPO_MOVIMENTO    VARCHAR(1) NOT NULL,
    QUANTIDADE        INTEGER NOT NULL,
    ESTOQUE_ANTERIOR  INTEGER,
    ESTOQUE_NOVO      INTEGER,
    USUARIO           VARCHAR(50),
    CONSTRAINT PK_MOVIMENTACOES PRIMARY KEY (ID),
    CONSTRAINT FK_MOV_PROD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID)
);

--Trigger
CREATE OR ALTER trigger TG_UPT_PRODUTOS for PRODUTOS
active after update position 0
AS
begin
IF (NEW.ESTOQUE_ATUAL IS DISTINCT FROM OLD.ESTOQUE_ATUAL) THEN
  BEGIN
    IF (NEW.ESTOQUE_ATUAL <> OLD.ESTOQUE_ATUAL) THEN
    BEGIN
      INSERT INTO MOVIMENTACOES_ESTOQUE
        (ID_PRODUTO,
         TIPO_MOVIMENTO,
         QUANTIDADE,
         ESTOQUE_ANTERIOR,
         DATA_HORA,
         USUARIO)
      VALUES
        (NEW.ID,
         'E',
         ABS(NEW.ESTOQUE_ATUAL - OLD.ESTOQUE_ATUAL),
         OLD.ESTOQUE_ATUAL,
         CURRENT_TIMESTAMP,
         'SISTEMA');
    END
    ELSE
    BEGIN
      INSERT INTO MOVIMENTACOES_ESTOQUE
        (ID_PRODUTO,
         TIPO_MOVIMENTO,
         QUANTIDADE,
         ESTOQUE_ANTERIOR,
         DATA_HORA,
         USUARIO)
      VALUES
        (NEW.ID,
         'S',
         ABS(NEW.ESTOQUE_ATUAL - OLD.ESTOQUE_ATUAL),
         OLD.ESTOQUE_ATUAL,
         CURRENT_TIMESTAMP,
         'SISTEMA');
    END
  END
end